/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.VIEW;

/**
 *
 * @author User
 */
public class CadastroUserGUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroUserGUI
     */
    public CadastroUserGUI() {
        initComponents();
        jTextArea1.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tela_cadastros = new javax.swing.JLabel();
        txtSubtitle = new javax.swing.JLabel();
        txtTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        txtParametros = new javax.swing.JLabel();
        txtSubparametros = new javax.swing.JLabel();
        txtSubparametos2 = new javax.swing.JLabel();
        txtSubparametros3 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Ajuda - Usuários");

        tela_cadastros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/IMG/login.png"))); // NOI18N

        txtSubtitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSubtitle.setText("Nesta tela de cadastro de usuários, apenas o administrador têm acesso!");

        txtTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTitle.setForeground(new java.awt.Color(255, 0, 0));
        txtTitle.setText("CADASTRO DE USUÁRIOS");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Botão \"SALVAR\" - Apenas salva com nome de usuário e senha\ndevidamentes preenchidos! Obs: selecione o perfil desejado.\n\nBotão \"EXCLUIR\" - Ao clicar é habilitado a interação com a\ntabela, clique no nome desejado e clique em excluir novamen-\nte! Obs: este botão é usado para erros de cadastro e não \nserá possivel excluir o usuário depois que ele já tenha \nfeito uma ficha.\n\nBotão \"CANCELAR\" - Apaga tudo, e retorna o foco para digi-\ntar tudo novamente, e bloqueia a interação com a tabela!");
        jScrollPane1.setViewportView(jTextArea1);

        txtParametros.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtParametros.setForeground(new java.awt.Color(255, 0, 0));
        txtParametros.setText("Parâmetros");

        txtSubparametros.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSubparametros.setText("Não é possível colocar espaços ou caracteres especiais no cadastro!");

        txtSubparametos2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSubparametos2.setText("Não é possível inserir usuário com o mesmo nome!");

        txtSubparametros3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSubparametros3.setText("No preenchimento da senha, os espaços não serão considerados para fazer login!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tela_cadastros)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(140, 140, 140)
                                        .addComponent(txtTitle))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtSubtitle)))
                                .addGap(0, 37, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtParametros)
                            .addComponent(txtSubparametros)
                            .addComponent(txtSubparametos2)
                            .addComponent(txtSubparametros3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSubtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addComponent(tela_cadastros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtParametros)
                .addGap(18, 18, 18)
                .addComponent(txtSubparametros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSubparametos2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSubparametros3)
                .addGap(0, 92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel tela_cadastros;
    private javax.swing.JLabel txtParametros;
    private javax.swing.JLabel txtSubparametos2;
    private javax.swing.JLabel txtSubparametros;
    private javax.swing.JLabel txtSubparametros3;
    private javax.swing.JLabel txtSubtitle;
    private javax.swing.JLabel txtTitle;
    // End of variables declaration//GEN-END:variables
}
