/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.VIEW;

import javax.swing.ImageIcon;

/**
 *
 * @author User
 */
public class FichasGUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form FichasGUI
     */
    public FichasGUI() {
        initComponents();
        txtTexto.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tela_cadastros = new javax.swing.JLabel();
        txtTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTexto = new javax.swing.JTextArea();
        txtParametros = new javax.swing.JLabel();
        txtSubparametros = new javax.swing.JLabel();
        txtSubparametros2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Ajuda - Fichas");

        tela_cadastros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/IMG/fichas.png"))); // NOI18N
        tela_cadastros.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtTitle.setForeground(new java.awt.Color(204, 0, 0));
        txtTitle.setText("CADASTROS DE FICHAS");

        txtTexto.setColumns(20);
        txtTexto.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtTexto.setRows(5);
        txtTexto.setText("Na tela de cadastros de fichas, deverá conter o nome\ncompleto, data de nascimento e atendimento apenas!\n\nBotão \"SALVAR\" - Ao clicar verifica se o nome realmente é\ncompleto,e se as datas informadas realmente existem! \nObs: Um exemplo seria dia 30/02, ou qualquer outra data \nque não existe no calendário.\n\nBotão \"EDITAR\" - Ao clicar habilita uma tabela com todas \nas fichas já cadastradas, ao clicar no nome da ficha ela \nautomaticamente preenche os campos, e o usuário poderá \neditar e clicar no botão \"OK\" ao lado do campo de \nATENDIMENTO! Obs: Ao clicar no OK, ele faz a mesma \nverificação que o botão SALVAR!\n\nBotão \"EXCLUIR\" - Só será habilitado quando for clicado \nno botão EDITAR, depois de clicar em EDITAR, clique no \nnome que está na tabela e depois de preencher automatica-\nmente os campos, clique em excluir!");
        jScrollPane1.setViewportView(txtTexto);

        txtParametros.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtParametros.setForeground(new java.awt.Color(204, 0, 0));
        txtParametros.setText("PARÂMETROS");

        txtSubparametros.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtSubparametros.setText("No campo do nome, não é permitido dois espaços e nem números!");

        txtSubparametros2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtSubparametros2.setText("As datas devem ser com 8 digitos e deverão existir!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tela_cadastros, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(txtTitle)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSubparametros2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSubparametros)
                                .addContainerGap(105, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtParametros)
                                .addGap(199, 199, 199))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tela_cadastros, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtTitle)
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtParametros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSubparametros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSubparametros2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel tela_cadastros;
    private javax.swing.JLabel txtParametros;
    private javax.swing.JLabel txtSubparametros;
    private javax.swing.JLabel txtSubparametros2;
    private javax.swing.JTextArea txtTexto;
    private javax.swing.JLabel txtTitle;
    // End of variables declaration//GEN-END:variables
}
