/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.VIEW;

import javax.swing.ImageIcon;

/**
 *
 * @author User
 */
public class PesquisaGUI extends javax.swing.JInternalFrame {

    /** Creates new form PesquisaGUI */
    public PesquisaGUI() {
        initComponents();
        txtTexto.setEnabled(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tela_pesquisa = new javax.swing.JLabel();
        txtTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTexto = new javax.swing.JTextArea();
        txtSubTitle = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Ajuda Pesquisa");

        tela_pesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/IMG/pesqui.png"))); // NOI18N

        txtTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtTitle.setForeground(new java.awt.Color(204, 0, 0));
        txtTitle.setText("Pesquisa de Fichas");

        txtTexto.setColumns(20);
        txtTexto.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtTexto.setRows(5);
        txtTexto.setText("Botão \"LISTAR TODOS\" - lista todas as\nfichas cadastradas desde o início.\nObs: Ao clicar nesse botão, será habili-\ntado 3 tipos de ordenação, por:\nNOME, DATA DE ATENDIMENTO E ÚLTIMA ATU-\nALIZAÇÃO!\n\nCampo de pesquisa avançada, ao digitar\numa letra por vez, irá aparecer fichas\ncontendo a cadeia de caracteres digitadas\nno início.\nObs: Ao começar a digitar será desabili-\ntado os tipos de ordenação.");
        jScrollPane1.setViewportView(txtTexto);

        txtSubTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSubTitle.setText("Nesta tela, existe 5 tipos de pesquisas:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tela_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                        .addComponent(txtTitle)
                        .addGap(70, 70, 70))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSubTitle)
                                .addGap(0, 106, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(txtTitle)
                        .addGap(28, 28, 28)
                        .addComponent(txtSubTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tela_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel tela_pesquisa;
    private javax.swing.JLabel txtSubTitle;
    private javax.swing.JTextArea txtTexto;
    private javax.swing.JLabel txtTitle;
    // End of variables declaration//GEN-END:variables

}
