/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.VIEW;

/**
 *
 * @author User
 */
public class RelatoriosGUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form RelatoriosGUI
     */
    public RelatoriosGUI() {
        initComponents();
        txtText.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tela_relatorio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTitle = new javax.swing.JLabel();
        txtSubtitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtText = new javax.swing.JTextArea();
        txtParametros = new javax.swing.JLabel();
        txtSubparametros = new javax.swing.JLabel();
        txtSubparametros2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Ajuda - Relatórios");

        tela_relatorio.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/IMG/tipo1.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/IMG/tipo2.png"))); // NOI18N

        javax.swing.GroupLayout tela_relatorioLayout = new javax.swing.GroupLayout(tela_relatorio);
        tela_relatorio.setLayout(tela_relatorioLayout);
        tela_relatorioLayout.setHorizontalGroup(
            tela_relatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tela_relatorioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tela_relatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        tela_relatorioLayout.setVerticalGroup(
            tela_relatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tela_relatorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtTitle.setForeground(new java.awt.Color(204, 0, 0));
        txtTitle.setText("Relatórios de Fichas Cadastradas");

        txtSubtitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSubtitle.setText("Nesta tela, existe 4 tipos de relatórios:");

        txtText.setColumns(20);
        txtText.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtText.setRows(5);
        txtText.setText("Relatórios entre datas: o usuário deverá informar a data de\ninício e fim, e clicar em IMPRIMIR, logo será apresentado\ntodas as fichas entre essas datas informadas!\n\nOutros tipos de relatórios: o usuário deverá selecionar o bo-\ntão \"OUTRO\" no canto inferior esquerdo, e será desabilitado\no relatório entre datas, e será liberado três tipos de rela-\ntórios por MÊS ATUAL, SEPARADO POR USUÁRIO E TUDO, escolha\num e clique em cima do nome e logo depois em IMPRIMIR!");
        jScrollPane1.setViewportView(txtText);

        txtParametros.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtParametros.setForeground(new java.awt.Color(204, 0, 0));
        txtParametros.setText("PARÂMETROS");

        txtSubparametros.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtSubparametros.setText("A data deverá ser correta e existir no calendário!");

        txtSubparametros2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtSubparametros2.setText("A data inicial tem que ser menor ou igual a final, ou o sistema não deixará imprimir!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tela_relatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(txtTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(txtSubtitle))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSubparametros)
                            .addComponent(txtSubparametros2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(txtParametros))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tela_relatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(txtTitle)
                .addGap(18, 18, 18)
                .addComponent(txtSubtitle)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(txtParametros)
                .addGap(18, 18, 18)
                .addComponent(txtSubparametros)
                .addGap(18, 18, 18)
                .addComponent(txtSubparametros2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel tela_relatorio;
    private javax.swing.JLabel txtParametros;
    private javax.swing.JLabel txtSubparametros;
    private javax.swing.JLabel txtSubparametros2;
    private javax.swing.JLabel txtSubtitle;
    private javax.swing.JTextArea txtText;
    private javax.swing.JLabel txtTitle;
    // End of variables declaration//GEN-END:variables
}
